//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UIBuilder.rc
//
#define ID_SEPARATOR                    0
#define ID_DEFAULT_PANE                 0
#define VS_VERSION_INFO                 1
#define IDC_MYICON                      2
#define IDD_UIBUILDER_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_UIBUILDER                   107
#define IDI_SMALL                       108
#define IDC_UIBUILDER                   109
#define IDR_UIBUILDER                   109
#define IDR_MAINFRAME                   128
#define IDD_PROJECT_TREE                129
#define IDD_NEW_PROJECT                 130
#define IDD_DIALOG_IMAGE_VIEW           131
#define IDD_NEW_IMAGE                   132
#define IDD_NEW_STYLE1                  132
#define IDD_NEW_STYLE2                  132
#define IDD_FIRST_PAGE                  133
#define IDB_TRANSPARENT_BK              134
#define IDD_DIALOG_COLOR_VIEW           134
#define IDD_NEW_COLOR                   135
#define IDD_DIALOG_FONT_VIEW            136
#define IDD_NEW_FONT                    137
#define IDD_DIALOG_LOG                  138
#define IDD_DIALOG_STYLE                139
#define IDD_DIALOG_STYLE_VIEW           139
#define IDD_DIALOG_IMAGE_BUILD          141
#define IDD_DIALOG_IMAGE_CODE           142
#define IDD_DIALOG_STYLE_BUILD          143
#define IDD_DIALOG_STYLE_CODE           144
#define IDD_DIALOG_WORKAREA             145
#define IDR_MENU1                       146
#define IDR_IMAGEBUILD                  146
#define IDD_DIALOG_FONT_BUILD           146
#define IDD_DIALOG_COLOR_BUILD          147
#define IDD_DIALOG_FONT_CODE            148
#define IDD_DIALOG_COLOR_CODE           149
#define IDD_NEW_STYLE                   150
#define IDD_NEW_STYLE_PROP              151
#define IDD_NEW_STYLE_ATTRIBUTE         151
#define IDD_DIALOG_LAYOUT_BUILD         152
#define IDD_DIALOG_STYLE_CODE1          153
#define IDD_DIALOG_LAYOUT_CODE          153
#define IDC_TREE                        1000
#define IDC_TREE_RES                    1000
#define IDC_EDIT_NEW_PROJECT_NAME       1001
#define IDC_EDIT_BROWSE                 1003
#define IDC_BUTTON_BROWSE               1004
#define IDC_EDIT_NEW_SKIN_NAME          1005
#define IDC_EDIT_IMAGE_XML_FILE         1006
#define IDC_FILELIST                    1008
#define IDC_EDIT_FONT_XML_FILE          1009
#define IDC_BUTTON_ADD                  1009
#define IDC_BUTTON_DELETE               1010
#define IDC_EDIT_ID                     1010
#define IDC_EDIT_COLOR_XML_FILE         1011
#define IDC_BUTTON_LEFT                 1011
#define IDC_EDIT_PATH                   1011
#define IDC_BUTTON_RIGHT                1012
#define IDC_CHECK_COPYFILE              1012
#define IDC_EDIT_LAYOUT_XML_FILE        1013
#define IDC_EDIT_XML_PATH               1014
#define IDC_EDIT_STYLE_XML_FILE         1015
#define IDC_BUTTON_NEW_PROJECT          1015
#define IDC_BTN_IMAGE_XML_BROWSE        1016
#define IDC_BUTTON_OPEN_PROJEC          1016
#define IDC_BUTTON_OPEN_PROJECT         1016
#define IDC_COLORLIST                   1016
#define IDC_BTN_FONT_XML_BROWSE         1017
#define IDC_EDIT_COLOR                  1017
#define IDC_BTN_COLOR_XML_BROWSE        1018
#define IDC_FONTLIST                    1018
#define IDC_EDIT_FONTSIZE               1018
#define IDC_BTN_LAYOUT_XML_BROWSE       1019
#define IDC_EDIT_FONTORIENTATION        1019
#define IDC_BTN_STYLE_XML_BROWSE        1020
#define IDC_CHECK_BOLD                  1020
#define IDC_EDIT_UI_XML_FILE            1021
#define IDC_CHECK_ITALIC                1021
#define IDC_BTN_UI_XML_BROWSE           1022
#define IDC_CHECK_UNDERLINE             1022
#define IDC_EDIT_FACENAME               1023
#define IDC_EDIT_LOG_XML_FILE           1024
#define IDC_CHECK_STRIKEOUT             1024
#define IDC_BTN_LOG_XML_BROWSE          1025
#define IDC_TAB                         1026
#define IDC_TREE_LOG                    1027
#define IDC_EDIT_MODULENAME             1028
#define IDC_COMBO_LOGLEVEL              1029
#define IDC_EDIT_LOGPATH                1030
#define IDC_BTN_BROWNSE                 1031
#define IDC_CHECK_LOGFLAG_CONSOLE       1032
#define IDC_CHECK_LOGPATH_RELATIVE      1033
#define IDC_CHECK_LOGFLAG_DEBUG         1035
#define IDC_CHECK_LOGFLAG_THREADID      1036
#define IDC_RADIO_FILEFALG_DONOTWRITEFILE 1037
#define IDC_RADIO_FILEFLAG_OVERWRITE    1038
#define IDC_RADIO_FILEFLAG_ADDTIMEEXT   1039
#define IDC_RADIO_FILEFLAG_LOOP         1040
#define IDC_EDIT_LOOPCOUNT              1041
#define IDC_SPIN_LOOPCOUNT              1042
#define IDC_CHECK_LOGITEM_SWITCH        1043
#define IDC_CHECK_LOGSWITCH             1045
#define IDC_BTN_LOG_SWITCH              1046
#define IDC_STATIC_GROPBOX              1049
#define IDC_BUTTON1                     1050
#define IDC_BTN_CHOOSECOL               1050
#define IDC_BUTTON_DELETE_SELECTOR      1051
#define IDC_BUTTON_ADD_SELECTOR         1052
#define IDC_BUTTON_MODIFY_SELECTOR      1053
#define IDC_STYLELIST                   1054
#define IDC_LIST_STYLE_PROP             1055
#define IDC_EDIT                        1056
#define IDC_BUTTON_REMOVE_PROP          1056
#define IDC_BUTTON_MODIFY_PROP          1057
#define IDC_TAB1                        1060
#define IDC_BTN_SAVE                    1061
#define IDC_COMBO1                      1062
#define IDC_COMBO_TYPE                  1062
#define IDC_LIST1                       1063
#define IDC_LISTBOX_STYLEITEM_NOT       1063
#define IDC_BUTTON_ADD_PROP             1064
#define IDC_LISTBOX_STYLEITEM_OWN       1064
#define IDC_EDIT_KEY                    1065
#define IDC_EDIT_VALUE                  1066
#define IDC_EDIT_INHERIT                1066
#define IDC_BUTTON_ADD_INHERIT          1067
#define IDC_BUTTON_DELETE_INHERIT       1068
#define IDC_BUTTON_CLEAR_INHERIT        1069
#define ATL_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define ID_NEW_PROJECT                  32772
#define ID_NEW_FILE                     32775
#define ID_OPEN_PROJECT                 32777
#define ID_NEW_SKIN                     32779
#define ID_MENU_MDI_MINIMIZE            32783
#define ID_MENU_MDI_RESTORE             32784
#define ID_MENU_MDI_CLOSE               32785
#define ID_32792                        32792
#define IDM_SAVE                        32793
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_PANE_CLOSE                   0xE152
#define ID_FORMAT_FONT                  0xE160
#define ID_SCROLL_UP                    0xE170
#define ID_SCROLL_DOWN                  0xE171
#define ID_SCROLL_PAGE_UP               0xE172
#define ID_SCROLL_PAGE_DOWN             0xE173
#define ID_SCROLL_TOP                   0xE174
#define ID_SCROLL_BOTTOM                0xE175
#define ID_SCROLL_LEFT                  0xE176
#define ID_SCROLL_RIGHT                 0xE177
#define ID_SCROLL_PAGE_LEFT             0xE178
#define ID_SCROLL_PAGE_RIGHT            0xE179
#define ID_SCROLL_ALL_LEFT              0xE17A
#define ID_SCROLL_ALL_RIGHT             0xE17B
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REFRESH                 0xE803
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define ID_WINDOW_TABFIRST              0xFF00
#define ID_WINDOW_TABLAST               0xFFFD
#define ID_WINDOW_SHOWTABLIST           0xFFFE
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
