#ifndef RENDERBASEDEFINE_H_90AE195E_F2CE_4420_943A_3C3B644464EC
#define RENDERBASEDEFINE_H_90AE195E_F2CE_4420_943A_3C3B644464EC

namespace  UI
{

const UINT  BUTTON_BKGND_RENDER_STATE_NORMAL  = RENDER_STATE_NORMAL|0;
const UINT  BUTTON_BKGND_RENDER_STATE_HOVER   = RENDER_STATE_HOVER|1;
const UINT  BUTTON_BKGND_RENDER_STATE_PRESS   = RENDER_STATE_PRESS|2;
const UINT  BUTTON_BKGND_RENDER_STATE_DISABLE = RENDER_STATE_DISABLE|3;
const UINT  BUTTON_BKGND_RENDER_STATE_DEFAULT = RENDER_STATE_DEFAULT|4;
const UINT  BUTTON_BKGND_RENDER_STATE_SELECTED_NORMAL   = RENDER_STATE_NORMAL|RENDER_STATE_SELECTED|4;
const UINT  BUTTON_BKGND_RENDER_STATE_SELECTED_HOVER    = RENDER_STATE_HOVER|RENDER_STATE_SELECTED|5;
const UINT  BUTTON_BKGND_RENDER_STATE_SELECTED_PRESS    = RENDER_STATE_PRESS|RENDER_STATE_SELECTED|6;
const UINT  BUTTON_BKGND_RENDER_STATE_SELECTED_DISABLE  = RENDER_STATE_DISABLE|RENDER_STATE_SELECTED|7;

const UINT  BUTTON_ICON_RENDER_STATE_NORMAL        = RENDER_STATE_NORMAL|0;
const UINT  BUTTON_ICON_RENDER_STATE_HOVER         = RENDER_STATE_HOVER|1;
const UINT  BUTTON_ICON_RENDER_STATE_PRESS         = RENDER_STATE_PRESS|2;
const UINT  BUTTON_ICON_RENDER_STATE_DISABLE       = RENDER_STATE_DISABLE|3;
const UINT  BUTTON_ICON_RENDER_STATE_SELECTED_NORMAL  = RENDER_STATE_NORMAL|RENDER_STATE_SELECTED|4;
const UINT  BUTTON_ICON_RENDER_STATE_SELECTED_HOVER   = RENDER_STATE_HOVER|RENDER_STATE_SELECTED|5;
const UINT  BUTTON_ICON_RENDER_STATE_SELECTED_PRESS   = RENDER_STATE_PRESS|RENDER_STATE_SELECTED|6;
const UINT  BUTTON_ICON_RENDER_STATE_SELECTED_DISABLE = RENDER_STATE_DISABLE|RENDER_STATE_SELECTED|7;


const UINT  EDIT_TEXTREDNER_STATE_NORMAL    = TEXTRENDER_STATE_NORMAL|0;
const UINT  EDIT_TEXTRENDER_STATE_SELECTED  = TEXTRENDER_STATE_SELECTED|1;

const UINT  EDIT_BKGND_RENDER_STATE_NORMAL  = RENDER_STATE_NORMAL|0;
const UINT  EDIT_BKGND_RENDER_STATE_HOVER   = RENDER_STATE_HOVER|1;
const UINT  EDIT_BKGND_RENDER_STATE_PRESS   = RENDER_STATE_PRESS|2;
const UINT  EDIT_BKGND_RENDER_STATE_DISABLE = RENDER_STATE_DISABLE|3;

const UINT  GROUPBOX_BKGND_RENDER_STATE_NORMAL     = RENDER_STATE_NORMAL|0;
const UINT  GROUPBOX_BKGND_RENDER_STATE_DISABLE    = RENDER_STATE_DISABLE|1;

const UINT  HEADERCTRL_ITEM_RENDER_STATE_NORMAL     = RENDER_STATE_NORMAL|0;
const UINT  HEADERCTRL_ITEM_RENDER_STATE_HOVER      = RENDER_STATE_HOVER|1;
const UINT  HEADERCTRL_ITEM_RENDER_STATE_PRESS      = RENDER_STATE_PRESS|2;
const UINT  HEADERCTRL_ITEM_RENDER_STATE_DISABLE    = RENDER_STATE_DISABLE|3;

const UINT  LISTBOX_BKGND_RENDER_STATE_NORMAL      = RENDER_STATE_NORMAL|0;
const UINT  LISTBOX_BKGND_RENDER_STATE_HOVER       = RENDER_STATE_HOVER|1;
const UINT  LISTBOX_BKGND_RENDER_STATE_PRESS       = RENDER_STATE_PRESS|2;
const UINT  LISTBOX_BKGND_RENDER_STATE_DISABLE     = RENDER_STATE_DISABLE|3;

const UINT  COMBOBOX_BKGND_RENDER_STATE_NORMAL     = RENDER_STATE_NORMAL|0;
const UINT  COMBOBOX_BKGND_RENDER_STATE_HOVER      = RENDER_STATE_HOVER|1;
const UINT  COMBOBOX_BKGND_RENDER_STATE_PRESS      = RENDER_STATE_PRESS|2;
const UINT  COMBOBOX_BKGND_RENDER_STATE_DISABLE    = RENDER_STATE_DISABLE|3;
const UINT  COMBOBOX_BKGND_RENDER_STATE_READONLY_NORMAL  = RENDER_STATE_READONLY |RENDER_STATE_NORMAL| 0;
const UINT  COMBOBOX_BKGND_RENDER_STATE_READONLY_HOVER   = RENDER_STATE_READONLY |RENDER_STATE_HOVER| 1;
const UINT  COMBOBOX_BKGND_RENDER_STATE_READONLY_PRESS   = RENDER_STATE_READONLY |RENDER_STATE_PRESS| 2;
const UINT  COMBOBOX_BKGND_RENDER_STATE_READONLY_DISABLE = RENDER_STATE_READONLY |RENDER_STATE_DISABLE| 3;

const UINT  MENU_BKGND_RENDER_STATE_NORMAL         = RENDER_STATE_NORMAL|0;

const UINT  MENU_STRING_ITEM_RENDER_STATE_NORMAL   = RENDER_STATE_NORMAL|0;
const UINT  MENU_STRING_ITEM_RENDER_STATE_HOVER    = RENDER_STATE_HOVER|1;
const UINT  MENU_STRING_ITEM_RENDER_STATE_PRESS    = RENDER_STATE_PRESS|2;
const UINT  MENU_STRING_ITEM_RENDER_STATE_DISABLE  = RENDER_STATE_DISABLE|3;

const UINT  MENU_ITEM_ICON_RENDER_STATE_NORMAL     = RENDER_STATE_NORMAL|0;
const UINT  MENU_ITEM_ICON_RENDER_STATE_HOVER      = RENDER_STATE_HOVER|1;
const UINT  MENU_ITEM_ICON_RENDER_STATE_PRESS      = RENDER_STATE_PRESS|2;
const UINT  MENU_ITEM_ICON_RENDER_STATE_DISABLE    = RENDER_STATE_DISABLE|3;

const UINT  MENU_POPUPTRIANGLE_RENDER_STATE_NORMAL = RENDER_STATE_NORMAL|0;
const UINT  MENU_POPUPTRIANGLE_RENDER_STATE_HOVER  = RENDER_STATE_HOVER|1;
const UINT  MENU_POPUPTRIANGLE_RENDER_STATE_PRESS  = RENDER_STATE_PRESS|2;
const UINT  MENU_POPUPTRIANGLE_RENDER_STATE_DISABLE = RENDER_STATE_DISABLE|3;

const UINT  TABCTRLBUTTON_BKGND_RENDER_STATE_NORMAL  = RENDER_STATE_NORMAL|0;
const UINT  TABCTRLBUTTON_BKGND_RENDER_STATE_HOVER   = RENDER_STATE_HOVER|1;
const UINT  TABCTRLBUTTON_BKGND_RENDER_STATE_SELECTED= RENDER_STATE_SELECTED|2;
const UINT  TABCTRLBUTTON_BKGND_RENDER_STATE_DISABLE = RENDER_STATE_DISABLE|3;
}
#endif // RENDERBASEDEFINE_H_90AE195E_F2CE_4420_943A_3C3B644464EC